/**
 * Guards on the mirror generator itself.
 *
 * The generator is what keeps the copied packages honest, so its rename has to
 * be provably faithful: whole-token, case-preserving, and never touching the
 * identifiers that belong to the *host* rather than to the tool.
 *
 * @module dsh-tool-zsh/test/mirror.test
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { root } from './helpers.mjs';
import { renameBashToZsh, stripBanner } from '../scripts/mirror-tool.mjs';

test('renames identifiers and prose in both cases', () => {
  assert.equal(renameBashToZsh('bashDescription'), 'zshDescription');
  assert.equal(renameBashToZsh('validateBashArgs'), 'validateZshArgs');
  assert.equal(renameBashToZsh('Execute a bash command (`bash -c`)'), 'Execute a zsh command (`zsh -c`)');
  assert.equal(renameBashToZsh('"tool-bash"'), '"tool-zsh"');
  assert.equal(renameBashToZsh('@deepseek-ai/dsh-tool-bash/render'), '@deepseek-ai/dsh-tool-zsh/render');
});

test('never rewrites the host section-order key', () => {
  const source = 'order: ctx.systemPrompt.getSectionOrder("TOOL_BASH"),';
  const renamed = renameBashToZsh(source);
  assert.equal(renamed, source, 'there is no TOOL_ZSH key; the zsh tool must reuse the bash slot');
});

test('round-trips to the original text', () => {
  const source = [
    'const name = "tool-bash";',
    'function bashDescription() {}',
    'order: ctx.systemPrompt.getSectionOrder("TOOL_BASH"),',
    '@module @deepseek-ai/dsh-tool-bash'
  ].join('\n');
  const renamed = renameBashToZsh(source);
  assert.equal(renamed.split('Zsh').join('Bash').split('zsh').join('bash'), source);
});

test('generated files are marked as generated and carry no stray bash naming', () => {
  const files = [
    'packages/tool-zsh/lib/index.js',
    'packages/tool-zsh/lib/types/index.d.ts',
    'packages/tool-zsh/lib/types/background.d.ts',
    'packages/tool-zsh/lib/types/render.d.ts'
  ];

  for (const relative of files) {
    const text = readFileSync(join(root, ...relative.split('/')), 'utf8');
    assert.ok(text.startsWith('// @generated by scripts/mirror-tool.mjs'), `${relative} is missing its banner`);

    // The banner names the upstream package on purpose; the body must not.
    const body = stripBanner(text);
    // Every remaining case-insensitive `bash` must belong to the one protected
    // host key; anything else is an un-renamed leftover.
    const mentions = body.match(/bash/gi) ?? [];
    const protectedKey = body.match(/TOOL_BASH/g) ?? [];
    assert.equal(
      mentions.length,
      protectedKey.length,
      `${relative} still mentions bash outside the protected TOOL_BASH key: ` +
        `${body.split('\n').filter((line) => /bash/i.test(line) && !line.includes('TOOL_BASH')).join(' | ')}`
    );
  }
});

test('the executor package carries no copied upstream source', () => {
  const text = readFileSync(join(root, 'packages', 'zsh-sandbox', 'lib', 'index.js'), 'utf8');
  assert.ok(
    text.includes('extends SandboxBashExecutor'),
    'the zsh executor must subclass the shipped one rather than fork it'
  );
  assert.ok(text.split('\n').length < 60, 'the executor should stay a thin subclass');
});
