/**
 * Keep `@yorkew-east8/dsh-tool-zsh` an exact, reviewable rename of the dsh
 * package it mirrors.
 *
 * `tool-zsh` is a behavioural clone of `@deepseek-ai/dsh-tool-bash`: the tool
 * name, its prompt section, its job kind and its approval subject all have to
 * say `zsh`, and none of that is parameterised upstream, so the only way to
 * ship it is to carry a renamed copy. A hand-maintained copy of 1400 lines
 * drifts silently every time dsh ships. This script makes the copy a *build
 * product* instead:
 *
 *   pnpm run sync          regenerate packages/tool-zsh from the installed dsh
 *   pnpm run check:mirror  fail loudly when the committed copy is stale
 *
 * The transform is deliberately a whole-token `bash` -> `zsh` rename with an
 * explicit protection list, and it is verified by the round-trip assertion in
 * `assertTransformIsFaithful()` below. Anything the transform cannot explain
 * shows up as a diff, which is the point.
 *
 * @module dsh-tool-zsh/scripts/mirror-tool
 */

import { readFileSync, writeFileSync, readdirSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { root, resolveDshPackagesDir, readVersion, isMain } from './dsh-packages.mjs';

/** Upstream package this repository mirrors. */
const UPSTREAM = '@deepseek-ai/dsh-tool-bash';
/** Our package directory. */
const TARGET_DIR = join(root, 'packages', 'tool-zsh');

/**
 * Tokens that must survive the rename untouched.
 *
 * `TOOL_BASH` is the one uppercase `BASH` in the upstream source: it is a key
 * into the *host* system-prompt section-order table. There is no `TOOL_ZSH`
 * key, and the correct behaviour is for the zsh tool's prompt section to
 * occupy the slot bash would have used, so this identifier stays as authored.
 */
const PROTECTED = ['TOOL_BASH'];

/** Marker used to park protected tokens during the rename. */
const PARK = '\u0000';

/**
 * Apply the bash -> zsh rename to one source text.
 *
 * @param source - upstream file contents.
 * @returns the renamed contents.
 */
export function renameBashToZsh(source) {
  let text = source;
  PROTECTED.forEach((token, index) => {
    text = text.split(token).join(`${PARK}${index}${PARK}`);
  });
  // `Bash` before `bash` so identifier and prose casing both survive.
  text = text.split('Bash').join('Zsh').split('bash').join('zsh');
  PROTECTED.forEach((token, index) => {
    text = text.split(`${PARK}${index}${PARK}`).join(token);
  });
  return text;
}

/**
 * Assert the rename is a faithful, reversible whole-token substitution.
 *
 * Guards the two ways this transform could quietly corrupt the mirror: a
 * protected token being rewritten, or an identifier being renamed in a way
 * that does not round-trip. Throws rather than writing a bad file.
 *
 * @param upstream - original upstream text.
 * @param renamed - result of {@link renameBashToZsh}.
 */
function assertTransformIsFaithful(upstream, renamed) {
  for (const token of PROTECTED) {
    const expected = upstream.split(token).length - 1;
    const actual = renamed.split(token).length - 1;
    if (expected !== actual) {
      throw new Error(`transform corrupted protected token ${token} (${expected} -> ${actual})`);
    }
  }
  const roundTrip = renamed.split('Zsh').join('Bash').split('zsh').join('bash');
  // Restoring case-sensitively only works when the upstream had no `zsh`
  // already; assert that precondition so the check below stays meaningful.
  if (upstream.includes('zsh')) {
    throw new Error('upstream already mentions zsh; the rename can no longer be verified by round-trip');
  }
  for (const token of PROTECTED) {
    if (roundTrip.split(token).length !== upstream.split(token).length) {
      throw new Error(`protected token ${token} did not survive the round-trip`);
    }
  }
}

/**
 * Strip the generated-file banner so drift checks compare code, not provenance.
 *
 * @param text - file contents.
 * @returns contents without a leading banner.
 */
export function stripBanner(text) {
  if (!text.startsWith('// @generated')) return text;
  let index = 0;
  for (let line = 0; line < BANNER_LINES; line += 1) index = text.indexOf('\n', index) + 1;
  return text.slice(index);
}

/** Number of lines {@link banner} emits; kept in step by an assertion below. */
const BANNER_LINES = 4;

/**
 * Compose the banner written at the top of every generated file.
 *
 * @param version - upstream version the mirror was generated from.
 * @param source - repository-relative upstream path.
 * @returns banner text including its trailing newline.
 */
function banner(version, source) {
  const text =
    `// @generated by scripts/mirror-tool.mjs from ${UPSTREAM}@${version}\n` +
    `// Source: ${source}\n` +
    `// Do not edit by hand: run \`pnpm run sync\` after upgrading dsh, and\n` +
    `// \`pnpm run check:mirror\` to detect drift.\n`;
  if (text.split('\n').length - 1 !== BANNER_LINES) {
    throw new Error('the generated banner no longer matches BANNER_LINES');
  }
  return text;
}

/** Files to mirror, as `{ from, to }` repository-relative paths. */
const FILES = [
  { from: 'lib/index.js', to: 'lib/index.js' },
  { from: 'lib/types/index.d.ts', to: 'lib/types/index.d.ts' },
  { from: 'lib/types/background.d.ts', to: 'lib/types/background.d.ts' },
  { from: 'lib/types/render.d.ts', to: 'lib/types/render.d.ts' }
];

/**
 * Compute the desired contents of every mirrored file.
 *
 * @param packagesDir - directory holding the dsh `@deepseek-ai/*` packages.
 * @returns `{ version, files }` where `files` maps target path to contents.
 */
function plan(packagesDir) {
  const upstreamDir = join(packagesDir, ...UPSTREAM.split('/'));
  const version = JSON.parse(readFileSync(join(upstreamDir, 'package.json'), 'utf8')).version;
  const files = new Map();

  for (const { from, to } of FILES) {
    const source = readFileSync(join(upstreamDir, from), 'utf8');
    const renamed = renameBashToZsh(source);
    assertTransformIsFaithful(source, renamed);
    files.set(to, banner(version, `${UPSTREAM}/${from}`) + renamed);
  }
  return { version, files };
}

/**
 * Report the first divergence between two texts in a readable form.
 *
 * @param expected - desired contents.
 * @param actual - committed contents.
 * @returns a message, or `undefined` when equal.
 */
function firstDifference(expected, actual) {
  const a = expected.split('\n');
  const b = actual.split('\n');
  for (let i = 0; i < Math.max(a.length, b.length); i += 1) {
    if (a[i] !== b[i]) {
      const context = [];
      for (let j = Math.max(0, i - 2); j < Math.min(i + 3, Math.max(a.length, b.length)); j += 1) {
        context.push(`  ${j + 1} expected: ${a[j] ?? '<eof>'}`);
        context.push(`  ${j + 1} actual:   ${b[j] ?? '<eof>'}`);
      }
      return `first difference at line ${i + 1}:\n${context.join('\n')}`;
    }
  }
  return undefined;
}

/** Delete mirrored `.d.ts` files that upstream no longer produces. */
function pruneStaleTypes(targetDir, files) {
  const typesDir = join(targetDir, 'lib', 'types');
  if (!existsSync(typesDir)) return [];
  const removed = [];
  for (const entry of readdirSync(typesDir)) {
    if (!entry.endsWith('.d.ts')) continue;
    const relative = `lib/types/${entry}`;
    if (files.has(relative)) continue;
    rmSync(join(typesDir, entry));
    removed.push(relative);
  }
  return removed;
}

/** Regenerate the mirror. */
export function write() {
  const packagesDir = resolveDshPackagesDir();
  const { version, files } = plan(packagesDir);
  const written = [];

  for (const [relative, contents] of files) {
    const path = join(TARGET_DIR, ...relative.split('/'));
    if (existsSync(path) && readFileSync(path, 'utf8') === contents) continue;
    writeFileSync(path, contents);
    written.push(relative);
  }
  const removed = pruneStaleTypes(TARGET_DIR, files);

  console.log(`${UPSTREAM}@${version} -> packages/tool-zsh`);
  for (const file of written) console.log(`  wrote   ${file}`);
  for (const file of removed) console.log(`  removed ${file}`);
  if (written.length === 0 && removed.length === 0) console.log('  already up to date');
}

/**
 * Read the upstream version recorded in a generated file's banner.
 *
 * @param text - file contents.
 * @returns the recorded version, or `undefined` when there is no banner.
 */
export function recordedVersion(text) {
  const match = /^\/\/ @generated by \S+ from \S+@(\S+)$/m.exec(text);
  return match?.[1];
}

/**
 * Verify the committed mirror matches the installed dsh.
 *
 * Pass/fail is decided on the *code* only: the banner records which upstream
 * version a file was generated from, and a release that changes nothing but its
 * version number must not be a failure. Such a release is reported as a note,
 * because the mirror is still functionally current -- it just has not been
 * re-stamped. Any difference below the banner is a genuine drift and fails.
 *
 * @returns process exit code.
 */
export async function check() {
  const packagesDir = resolveDshPackagesDir();
  const installed = await readVersion(packagesDir, UPSTREAM);
  const { files } = plan(packagesDir);
  const problems = [];
  const staleStamps = new Set();

  for (const [relative, contents] of files) {
    const path = join(TARGET_DIR, ...relative.split('/'));
    if (!existsSync(path)) {
      problems.push(`${relative}: missing`);
      continue;
    }
    const actual = readFileSync(path, 'utf8');
    const difference = firstDifference(stripBanner(contents), stripBanner(actual));
    if (difference !== undefined) problems.push(`${relative}: ${difference}`);
    else if (recordedVersion(actual) !== installed) staleStamps.add(recordedVersion(actual) ?? 'unknown');
  }

  if (problems.length > 0) {
    console.error(`packages/tool-zsh is out of sync with ${UPSTREAM}@${installed}:`);
    for (const problem of problems) console.error(`  ${problem}`);
    console.error('\nRun `pnpm run sync`, review the diff, and commit.');
    return 1;
  }

  if (staleStamps.size > 0) {
    console.log(
      `note: code matches ${UPSTREAM}@${installed}, but the banner still records ` +
        `${[...staleStamps].join(', ')}. Run \`pnpm run sync\` to refresh it.`
    );
  }
  console.log(`packages/tool-zsh matches ${UPSTREAM}@${installed}`);
  return 0;
}

if (isMain(import.meta.url)) {
  const mode = process.argv.includes('--check') ? 'check' : process.argv.includes('--write') ? 'write' : undefined;
  if (mode === undefined) {
    console.error('usage: node scripts/mirror-tool.mjs --write | --check');
    process.exit(2);
  }
  process.exit(mode === 'write' ? (write(), 0) : await check());
}
